### ISSUE TITLE
java.net.SocketTimeoutException: failed to connect to cfg.imtt.qq.com/13.127.247.216 (port 443) from /192.168.1.51 (port 42096) after 20000ms

### ISSUE THREAD

**Issue by dishant-livebird** [LiWenHui96/flutter_file_view#17]
Failed to initiaize engine.

`W/System.err: java.net.SocketTimeoutException: failed to connect to cfg.imtt.qq.com/13.127.247.216 (port 443) from /192.168.1.51 (port 42096) after 20000ms
W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:179)
W/System.err:     at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
W/System.err:     at java.net.Socket.connect(Socket.java:646)
W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
W/System.err:     at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
W/System.err:     at com.tencent.smtt.utils.g.b(Unknown Source:1)
W/System.err:     at com.tencent.smtt.utils.g.a(Unknown Source:121)
W/System.err:     at com.tencent.smtt.sdk.TbsDownloader.b(Unknown Source:519)
W/System.err:     at com.tencent.smtt.sdk.TbsDownloader.a(Unknown Source:0)
W/System.err:     at com.tencent.smtt.sdk.TbsDownloader$2.handleMessage(Unknown Source:271)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err:     at android.os.Looper.loopOnce(Looper.java:226)
W/System.err:     at android.os.Looper.loop(Looper.java:313)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)
W/System.err: org.json.JSONException: Value ["HttpError"] of type org.json.JSONArray cannot be converted to JSONObject
W/System.err:     at org.json.JSON.typeMismatch(JSON.java:112)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:172)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:185)
W/System.err:     at com.tencent.smtt.sdk.TbsDownloader.a(Unknown Source:78)
W/System.err:     at com.tencent.smtt.sdk.TbsDownloader.b(Unknown Source:568)
W/System.err:     at com.tencent.smtt.sdk.TbsDownloader.a(Unknown Source:0)
W/System.err:     at com.tencent.smtt.sdk.TbsDownloader$2.handleMessage(Unknown Source:271)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err:     at android.os.Looper.loopOnce(Looper.java:226)
W/System.err:     at android.os.Looper.loop(Looper.java:313)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)`

**Comment by LiWenHui96** [comment]
当前的使用环境，是否为局域网？并提供下机型和Android版本。

**Comment by dishant-livebird** [comment]
I run your package GitHub example in android os version 12 and Samsung f23 mobile model with wifi connected.
